In [23]:
import numpy as np

In [24]:
arr = np.array([[10, 20, 30, 40],
                [500, 600, 700, 800]])
print(arr)
print(type(arr))

[[ 10  20  30  40]
 [500 600 700 800]]
<class 'numpy.ndarray'>


In [25]:
A = np.array([200,600,800,1200])
print("Array of 1D :-", A[1:3])
print("Array of 2D:-",arr[0:2,0:3])

Array of 1D :- [600 800]
Array of 2D:- [[ 10  20  30]
 [500 600 700]]


In [26]:
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)
print(arr.astype(float))

(2, 4)
8
2
int64
[[ 10.  20.  30.  40.]
 [500. 600. 700. 800.]]


In [27]:
arr1 = np.array([[20,30],[40,50]])
arr2 = np.array([[60,80],[50,70]])
print(arr1+arr2)
print(np.add(arr1,arr2))
#same for subtract , multiply and division

[[ 80 110]
 [ 90 120]]
[[ 80 110]
 [ 90 120]]


In [28]:
arr6 = np.array([3,4,2,1])
arr7 = np.array([2])
print(np.power(arr6,arr7))

[ 9 16  4  1]


In [29]:
arr3 = np.array([ 9,16,4,1])
print(np.sqrt(arr3))

[3. 4. 2. 1.]


In [34]:
A1 = np.array([30,70,80])
B2 = np.array([55,77,88])
print(A1+B2)
print(np.concatenate([A1,B2]))


[ 85 147 168]
[30 70 80 55 77 88]


In [35]:
A1 = [30,70,80]
B2 = [55,77,88]
print(A1+B2)

[30, 70, 80, 55, 77, 88]


In [38]:
print(np.concatenate([arr1,arr2], axis = 1))

[[20 30 60 80]
 [40 50 50 70]]


In [ ]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[20 30 60 80]
 [40 50 50 70]]


In [ ]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[20 30]
 [40 50]
 [60 80]
 [50 70]]


In [48]:
a = np.array([20,40,50,60,80,90])
c = np.array([[20,40,50],[60,80,90]])
b = np.array_split(a,4)
d =  np.array_split(c,4)
print(b)
print(d)

[array([20, 40]), array([50, 60]), array([80]), array([90])]
[array([[20, 40, 50]]), array([[60, 80, 90]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [50]:
c = np.array([[20,40,50],[60,80,90]])
print(np.delete(c,1, axis = 1))

[[20 50]
 [60 90]]


In [52]:
ar = np.array([2,4,6,8,10])
ar2 = np.array([5,6,8,20,7])
t = np.where(ar2 % 2 == 0)
s = np.where(ar % 2 == 0)
print(s)
print(t)

(array([0, 1, 2, 3, 4]),)
(array([1, 2, 3]),)


In [ ]:
ss = np.array([1,2,3,5,7,8])
u = np.searchsorted(ss,10) #“At which index can I insert 10 while keeping the array sorted?”
print(u)
print(ss)

6
[1 2 3 5 7 8]


In [58]:
arrr = np.array([30,60,80,50.70])
fa = arrr > 54
new = arrr[fa]
print(new)



[60. 80.]


In [59]:
C3 = np.array([30,80,90,40,50,60])
print(np.sum(C3))
print(np.min(C3))
print(np.max(C3))
print(np.size(C3))
print(np.mean(C3))
print(np.cumsum(C3))
print(np.cumprod(C3))


350
30
90
6
58.333333333333336
[ 30 110 200 240 290 350]
[         30        2400      216000     8640000   432000000 25920000000]


In [64]:
p = [100,150,199,200,250,130]
q = [10,50,30,40,30,10]
price = np.array(p)
quantity = np.array(q)

print(price,"\n",quantity)
print()
tot = np.cumprod([price, quantity], axis=0)

print(tot)
print(tot[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270


In [68]:
import statistics as stats
baked_food = [200,300,150,130,200,280,170,188]
a = np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))



202.25
194.0
200
55.68157235567257
3100.4375


In [69]:
tabacco_consumption = [20,30,80,70,60]
deaths = [100,500,700,800,900]
print(np.corrcoef([tabacco_consumption,deaths]))

[[1.         0.82464375]
 [0.82464375 1.        ]]


In [70]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
